#!/bin/bash -l

### Job Name
#PBS -N gdex-web-service-transform
### Charging account
#PBS -A P43713000
### Request one chunk of resources with 1 CPU and 10 GB of memory
#PBS -l select=1:ncpus=1:mem=1GB
### Allow job to run up to 1 hour 30 minutes
#PBS -l walltime=00:05:00
### Route the job to the casper queue
#PBS -q gdex
### Join output and error streams into single file
#PBS -j oe

# Environment Management
module --force purge
# module load ncarenv/24.12
# module load conda
# conda activate /glade/work/gdexdata/conda-envs/pg-gdex
source /glade/u/home/chiaweih/gdex-web-services/test-gdexws-env/bin/activate


### Parse positional arguments
PAYLOAD="https://boreas.hpc.ucar.edu:6443/gdex-data/services_tmp/payloads/transform.payload.json"
# PAYLOAD="/glade/u/home/chiaweih/gdex-web-services/tests/test.payload.json"
# CINDEX="1"


### SETUP .jsonl
jsonl_dir="/glade/campaign/collections/gdex/data/exchange/Web-services/"
output_jsonl="$jsonl_dir/$CINDEX.gdexws.jsonl"

# Clear or create file
> "$output_jsonl"
echo "This is the $CINDEX. This is the $output_jsonl. This is the $PAYLOAD" >> "$output_jsonl"

# Shell start message
time_iso=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
echo '{"command": "pbs", "time_of_process": "'"$time_iso"'", "level": "INFO", "process_message": "PBS job started"}' >> "$output_jsonl"

# Execute transform (the payload can be Boreas link)
transform -p "$PAYLOAD" >> "$output_jsonl"
EXIT_CODE=$?

# Shell end message
time_iso=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
if [ $EXIT_CODE -eq 0 ]; then
    echo '{"command": "pbs", "time_of_process": "'"$time_iso"'", "level": "INFO", "process_message": "PBS job completed"}' >> "$output_jsonl"
else
    echo '{"command": "pbs", "time_of_process": "'"$time_iso"'", "level": "ERROR", "process_message": "PBS job failed", "exit_code": '"$EXIT_CODE"'}' >> "$output_jsonl"
fi
