apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery
  namespace: {{ .Release.Namespace }}
  labels:
    app: celery
    group: {{ .Values.webapp.group }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery
  template:
    metadata:
      labels:
        app: celery
    spec:
      volumes:
      - name: {{ .Values.webapp.volume.name }}
        nfs:
          server: {{ .Values.webapp.volume.server }}
          path: {{ .Values.webapp.volume.path }}
          readOnly: {{ .Values.webapp.volume.readOnly }}
      containers:
      - name: celery
        image: "{{ .Values.webapp.container.image }}"
        command:
          - celery
          - -A
          - app.celery_app
          - worker
          - --loglevel=INFO
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: "0.5"
            memory: 1Gi
        volumeMounts:
        - mountPath: {{ .Values.webapp.volume.mountPath }}
          name: {{ .Values.webapp.volume.name }}
          readOnly: {{ .Values.webapp.volume.readOnly }}
