apiVersion: apps/v1
kind: Deployment
metadata:
  {{ if .Values.testName }}
  name: {{ .Values.testName }}-{{ .Values.webapp.name }}
  {{ else }}
  name: {{ .Values.webapp.name }}
  {{ end }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{ if .Values.testName }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/name: {{ .Values.testName }}-gdex-web-services
    app.kubernetes.io/instance: {{ .Values.testName }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app: {{ .Values.testName }}-{{ .Values.webapp.name }}
    {{ else }}
    app: {{ .Values.webapp.name }}
    {{ end }}
    group: {{ .Values.webapp.group }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{ if .Values.testName }}
      app: {{ .Values.testName }}-{{ .Values.webapp.name }}
      app.kubernetes.io/instance: {{ .Values.testName }}
      {{ else }}
      app: {{ .Values.webapp.name }}
      {{ end }}
  template:
    metadata:
      labels:
        {{ if .Values.testName }}
        app: {{ .Values.testName }}-{{ .Values.webapp.name }}
        app.kubernetes.io/instance: {{ .Values.testName }}
        {{ else }}
        app: {{ .Values.webapp.name }}
        {{ end }}
    spec:
      volumes:
      - name: {{ .Values.webapp.volume.name }}
        nfs:
          server: {{ .Values.webapp.volume.server }}
          path: {{ .Values.webapp.volume.path }}
          readOnly: {{ .Values.webapp.volume.readOnly }}
      containers:
      {{ if .Values.testName }}
      - name: {{ .Values.testName }}-{{ .Values.webapp.name }}
      {{ else }}
      - name: {{ .Values.webapp.name }}
      {{ end }}
        image: {{ .Values.webapp.container.image }}
        imagePullPolicy: Always
        resources:
          requests:
            memory: {{ .Values.webapp.container.requests.memory }}
            cpu: {{ .Values.webapp.container.requests.cpu }}
          limits:
            memory: {{ .Values.webapp.container.limits.memory }}
            cpu: {{ .Values.webapp.container.limits.cpu }}
        ports:
        - containerPort: {{ .Values.webapp.container.port }}
        env:
        - name: OBJECT_STORE_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: {{ .Values.webapp.objectStore.secretName }}
              key: access_key_id
        - name: OBJECT_STORE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.webapp.objectStore.secretName }}
              key: secret_key
        - name: BAOTOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Values.webapp.baoToken.existingSecret.name }}
              key: {{ .Values.webapp.baoToken.existingSecret.key }}
        - name: PGDB01_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.webapp.pgdb01Secret.existingSecret.name }}
              key: {{ .Values.webapp.pgdb01Secret.existingSecret.key }}
        volumeMounts:
        - mountPath: {{ .Values.webapp.volume.mountPath }}
          name: {{ .Values.webapp.volume.name }}
          readOnly: {{ .Values.webapp.volume.readOnly }}
