apiVersion: apps/v1
kind: Deployment
metadata:
  {{ if .Values.testName }}
  name: {{ .Values.testName }}-{{ .Values.webapp.name }}
  {{ else }}
  name: {{ .Values.webapp.name }}
  {{ end }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{ if .Values.testName }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/name: {{ .Values.testName }}-gdex-web-services
    app.kubernetes.io/instance: {{ .Values.testName }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app: {{ .Values.testName }}-{{ .Values.webapp.name }}
    {{ else }}
    app: {{ .Values.webapp.name }}
    {{ end }}
    group: {{ .Values.webapp.group }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{ if .Values.testName }}
      app: {{ .Values.testName }}-{{ .Values.webapp.name }}
      app.kubernetes.io/instance: {{ .Values.testName }}
      {{ else }}
      app: {{ .Values.webapp.name }}
      {{ end }}
  template:
    metadata:
      labels:
        {{ if .Values.testName }}
        app: {{ .Values.testName }}-{{ .Values.webapp.name }}
        app.kubernetes.io/instance: {{ .Values.testName }}
        {{ else }}
        app: {{ .Values.webapp.name }}
        {{ end }}
    spec:
      containers:
      {{ if .Values.testName }}
      - name: {{ .Values.testName }}-{{ .Values.webapp.name }}
      {{ else }}
      - name: {{ .Values.webapp.name }}
      {{ end }}
        image: {{ .Values.webapp.container.image }}
        imagePullPolicy: Always
        resources:
          requests:
            memory: {{ .Values.webapp.container.requests.memory }}
            cpu: {{ .Values.webapp.container.requests.cpu }}
          limits:
            memory: {{ .Values.webapp.container.limits.memory }}
            cpu: {{ .Values.webapp.container.limits.cpu }}
        ports:
        - containerPort: {{ .Values.webapp.container.port }}
        {{ if .Values.volume }}
        volumeMounts:
        - mountPath: {{ .Values.volume.fs.mountPath }}
          name: {{ .Values.volume.fs.name }}
          {{ if .Values.testName }}
          readOnly: true
          {{ end }}
      volumes:
      - name: {{ .Values.volume.fs.name }}
        persistentVolumeClaim:
          claimName: {{ .Values.volume.fs.name }}
        {{ end }}
