apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  {{ if .Values.testName }}
  name: {{ .Values.testName }}-{{ .Values.webapp.name }}-dbconnect
  {{ else }}
  name: {{ .Values.webapp.name }}-dbconnect
  {{ end }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: rda-ro
    kind: SecretStore
  target:
    name: pgdb0102-superuser
  data:
    - secretKey: password
      remoteRef:
        key: {{ .Values.webapp.externalSecret.baoPath }}
        property: password
    - secretKey: dssdbpass
      remoteRef:
        key: {{ .Values.webapp.externalSecret.baoPath }}
        property: dssdbpass
    - secretKey: metapass
      remoteRef:
        key: {{ .Values.webapp.externalSecret.baoPath }}
        property: metapass
    - secretKey: wagtailpass
      remoteRef:
        key: {{ .Values.webapp.externalSecret.baoPath }}
        property: wagtailpass
