apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Webapp.Name }}-dbconnect
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: rda-ro
    kind: SecretStore
  target:
    name: pgdb0102-superuser
  data:
    - secretKey: password
      remoteRef:
        key: {{ .Webapp.ExternalSecret.baoPath }}
        property: password
    - secretKey: dssdbpass
      remoteRef:
        key: {{ .Webapp.ExternalSecret.baoPath }}
        property: dssdbpass
    - secretKey: metapass
      remoteRef:
        key: {{ .Webapp.ExternalSecret.baoPath }}
        property: metapass
    - secretKey: wagtailpass
      remoteRef:
        key: {{ .Webapp.ExternalSecret.baoPath }}
        property: wagtailpass
