{{- if .Values.redis.deploy }}
{{- $redisName := .Values.redis.name }}
{{- if .Values.testName }}
{{- $redisName = printf "%s-%s" .Values.testName .Values.redis.name }}
{{- end }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $redisName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ $redisName }}
    {{- if .Values.testName }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/name: {{ .Values.testName }}-gdex-web-services
    app.kubernetes.io/instance: {{ .Values.testName }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- end }}
    group: {{ .Values.webapp.group }}
spec:
  selector:
    app: {{ $redisName }}
    {{- if .Values.testName }}
    app.kubernetes.io/instance: {{ .Values.testName }}
    {{- end }}
  ports:
  - port: {{ .Values.redis.port }}
    targetPort: {{ .Values.redis.port }}
{{- end }}
